export const API_CONFIG = {
  BASE_URL: 'https://invenza.onrender.com',
  TIMEOUT: 30000,
  ENDPOINTS: {
    AUTH: {
      REGISTER: '/api/auth/register',
      LOGIN: '/api/auth/login',
      LOGOUT: '/api/auth/logout',
      REFRESH: '/api/auth/refresh',
      VERIFY_EMAIL: '/api/auth/verify-email',
      FORGOT_PASSWORD: '/api/auth/forgot-password',
      RESET_PASSWORD: '/api/auth/reset-password',
      CHANGE_PASSWORD: '/api/auth/change-password',
    },
    BUSINESS: {
      GET: (id: string) => `/api/business/${id}`,
      UPDATE: (id: string) => `/api/business/${id}`,
      UPLOAD_DOC: (id: string) => `/api/business/${id}/doc`,
      SETTINGS: (id: string) => `/api/business/${id}/settings`,
    },
    ITEMS: {
      LIST: '/api/items',
      CREATE: '/api/items',
      GET: (id: string) => `/api/items/${id}`,
      UPDATE: (id: string) => `/api/items/${id}`,
      ADJUST: (id: string) => `/api/items/${id}/adjust`,
      SCAN: (id: string) => `/api/items/${id}/scan`,
      EVENTS: (id: string) => `/api/items/${id}/events`,
    },
    TAGS: {
      LIST: '/api/tags',
      REGISTER: '/api/tags/register',
      GET: (tagId: string) => `/api/tags/${tagId}`,
    },
    SYNC: {
      PUSH: '/api/sync/push',
      PULL: '/api/sync/pull',
      CONFLICTS: '/api/sync/conflicts',
      STATUS: '/api/sync/status',
      DEDUPLICATE: '/api/sync/deduplicate',
      CLEANUP: '/api/sync/cleanup',
    },
    DEVICES: {
      REGISTER: '/api/devices/register',
    },
    NOTIFICATIONS: {
      LIST: '/api/notifications',
      UNREAD_COUNT: '/api/notifications/unread-count',
      MARK_READ: (id: string) => `/api/notifications/${id}/read`,
      MARK_ALL_READ: '/api/notifications/read-all',
      DELETE: (id: string) => `/api/notifications/${id}`,
    },
    ALERTS: {
      LIST: '/api/alerts',
      RESOLVE: (id: string) => `/api/alerts/${id}/resolve`,
      CHECK: '/api/alerts/check',
    },
    REPORTS: {
      STOCK_SUMMARY: '/api/reports/stock-summary',
      LOW_STOCK: '/api/reports/low-stock',
      USAGE_TRENDS: '/api/reports/usage-trends',
      TOP_SELLING: '/api/reports/top-selling',
      CATEGORY_BREAKDOWN: '/api/reports/category-breakdown',
    },
  },
};
